version: '3'

services:
# web用コンテナー
  web:
    build: ./web
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    stdin_open: true

# webサーバー
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    depends_on: 
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro